# Конфигурация ZeroEvents

# Настройки ивента с вазой
vase-event:
  # Интервал между ивентами в минутах (0 = отключено)
  interval: 0

  # Координаты спавна вазы
  location:
    world: "world"
    x: 112
    y: 16
    z: 197

  # Общие настройки дропа (для всех редкостей)
  drops:
    # Интервал между дропами в ТИКАХ (20 тиков = 1 секунда)
    interval-ticks: 50
    # Скорость выброса предметов
    velocity:
      min: 0.40
      max: 0.55

  # Настройки для каждой редкости
  rarities:
    default:
      # Количество дропов
      drops:
        amount: 6
      # Время жизни вазы в секундах
      lifetime-seconds: 300
      # Голограмма над вазой
      hologram:
        - "&7Обычная ваза"
      # Сообщение при старте
      start-message: "&#909EF3ᴢ&#7994F4ᴇ&#618BF5ʀ&#4A81F6ᴏ&#3377F6ʙ&#1B6EF7ᴏ&#0464F8x &7● &fОбычная ваза появилась на координатах: &b%x%, %y%, %z%"

    rare:
      drops:
        amount: 7
      lifetime-seconds: 300
      hologram:
        - "&9&lРЕДКАЯ ВАЗА"
      start-message: "&#909EF3ᴢ&#7994F4ᴇ&#618BF5ʀ&#4A81F6ᴏ&#3377F6ʙ&#1B6EF7ᴏ&#0464F8x &7● &9&lРЕДКАЯ &9ваза появилась на координатах: &b%x%, %y%, %z%"

    mythic:
      drops:
        amount: 8
      lifetime-seconds: 300
      hologram:
        - "&c&lМИФИЧЕСКАЯ ВАЗА"
      start-message: "&#909EF3ᴢ&#7994F4ᴇ&#618BF5ʀ&#4A81F6ᴏ&#3377F6ʙ&#1B6EF7ᴏ&#0464F8x &7● &c&lМИФИЧЕСКАЯ &cваза появилась на координатах: &b%x%, %y%, %z%"

    legendary:
      drops:
        amount: 9
      lifetime-seconds: 300
      hologram:
        - "&6&lЛЕГЕНДАРНАЯ ВАЗА"
      start-message: "&#909EF3ᴢ&#7994F4ᴇ&#618BF5ʀ&#4A81F6ᴏ&#3377F6ʙ&#1B6EF7ᴏ&#0464F8x &7● &6&lЛЕГЕНДАРНАЯ &6ваза появилась на координатах: &b%x%, %y%, %z%"

# Настройки ивента с шалкерами
shulker-event:
  # Интервал между ивентами в минутах (0 = отключено)
  interval: 0

  # Локации спавна шалкеров
  locations:
    1:
      world: "world"
      x: 258
      y: -16
      z: 219
    2:
      world: "world"
      x: 198
      y: 23
      z: 257
    3:
      world: "world"
      x: 187
      y: 12
      z: 187
    4:
      world: "world"
      x: 179
      y: -23
      z: 230
    5:
      world: "world"
      x: 244
      y: 2
      z: 266

  # Настройки для каждой редкости
  rarities:
    default:
      # Количество ударов для разрушения
      hits: 50
      # Время жизни шалкера в секундах
      lifetime-seconds: 300
      # Количество предметов при разрушении
      drops:
        amount: 5
      # Голограмма
      hologram:
        - "&7Обычный шалкер"
        - "&f[&e%hits%&f/&e%max%&f]"
      # Сообщение при спавне
      start-message: "&#909EF3ᴢ&#7994F4ᴇ&#618BF5ʀ&#4A81F6ᴏ&#3377F6ʙ&#1B6EF7ᴏ&#0464F8x &7● &fОбычные шалкеры появились в мире!"

    rare:
      hits: 80
      lifetime-seconds: 300
      drops:
        amount: 7
      hologram:
        - "&9&lРЕДКИЙ ШАЛКЕР"
        - "&f[&b%hits%&f/&b%max%&f]"
      start-message: "&#909EF3ᴢ&#7994F4ᴇ&#618BF5ʀ&#4A81F6ᴏ&#3377F6ʙ&#1B6EF7ᴏ&#0464F8x &7● &9&lРЕДКИЕ &9шалкеры появились в мире!"

    mythic:
      hits: 100
      lifetime-seconds: 300
      drops:
        amount: 10
      hologram:
        - "&c&lМИФИЧЕСКИЙ ШАЛКЕР"
        - "&f[&6%hits%&f/&6%max%&f]"
      start-message: "&#909EF3ᴢ&#7994F4ᴇ&#618BF5ʀ&#4A81F6ᴏ&#3377F6ʙ&#1B6EF7ᴏ&#0464F8x &7● &c&lМИФИЧЕСКИЕ &cшалкеры появились в мире!"

    legendary:
      hits: 150
      lifetime-seconds: 300
      drops:
        amount: 15
      hologram:
        - "&6&l&nЛЕГЕНДАРНЫЙ ШАЛКЕР"
        - "&e&l✦ &f[&e%hits%&f/&e%max%&f] &e&l✦"
      start-message: "&#909EF3ᴢ&#7994F4ᴇ&#618BF5ʀ&#4A81F6ᴏ&#3377F6ʙ&#1B6EF7ᴏ&#0464F8x &7● &6&lЛЕГЕНДАРНЫЕ &6шалкеры появились в мире!"

# Настройки ивента с пальмой изобилия
palm-event:
  # Интервал между ивентами в минутах (0 = отключено)
  interval: 0

  # Время жизни пальмы в секундах
  lifetime-seconds: 300

  # Высота падения кокосов
  fall-height: 26.5

  # Локации спавна пальм (5 точек)
  locations:
    1:
      world: "world"
      x: 19
      y: -31
      z: 85
    2:
      world: "world"
      x: 31
      y: -39
      z: 95
    3:
      world: "world"
      x: 18
      y: -31
      z: 106
    4:
      world: "world"
      x: 11
      y: -27
      z: 96
    5:
      world: "world"
      x: 16
      y: -27
      z: 96

  # Настройки для каждой редкости
  rarities:
    default:
      drops:
        amount: 3
      start-message: "&#909EF3ᴢ&#7994F4ᴇ&#618BF5ʀ&#4A81F6ᴏ&#3377F6ʙ&#1B6EF7ᴏ&#0464F8x &7● &fПальмы изобилия появились в мире!"

    rare:
      drops:
        amount: 5
      start-message: "&#909EF3ᴢ&#7994F4ᴇ&#618BF5ʀ&#4A81F6ᴏ&#3377F6ʙ&#1B6EF7ᴏ&#0464F8x &7● &9&lРЕДКИЕ &9пальмы изобилия появились!"

    mythic:
      drops:
        amount: 7
      start-message: "&#909EF3ᴢ&#7994F4ᴇ&#618BF5ʀ&#4A81F6ᴏ&#3377F6ʙ&#1B6EF7ᴏ&#0464F8x &7● &c&lМИФИЧЕСКИЕ &cпальмы изобилия появились!"

    legendary:
      drops:
        amount: 10
      start-message: "&#909EF3ᴢ&#7994F4ᴇ&#618BF5ʀ&#4A81F6ᴏ&#3377F6ʙ&#1B6EF7ᴏ&#0464F8x &7● &6&lЛЕГЕНДАРНЫЕ &6пальмы изобилия появились!"

# Сообщения
messages:
  event-end: "&#909EF3ᴢ&#7994F4ᴇ&#618BF5ʀ&#4A81F6ᴏ&#3377F6ʙ&#1B6EF7ᴏ&#0464F8x &7● &cИвент с вазой закончился!"
  vase-timeout: "&#909EF3ᴢ&#7994F4ᴇ&#618BF5ʀ&#4A81F6ᴏ&#3377F6ʙ&#1B6EF7ᴏ&#0464F8x &7● &cВаза исчезла из-за истечения времени!"
  shulker-destroyed: "&#909EF3ᴢ&#7994F4ᴇ&#618BF5ʀ&#4A81F6ᴏ&#3377F6ʙ&#1B6EF7ᴏ&#0464F8x &7● &cШалкер разрушен!"
  shulker-timeout: "&#909EF3ᴢ&#7994F4ᴇ&#618BF5ʀ&#4A81F6ᴏ&#3377F6ʙ&#1B6EF7ᴏ&#0464F8x &7● &cШалкеры исчезли из-за истечения времени!"
  palm-timeout: "&#909EF3ᴢ&#7994F4ᴇ&#618BF5ʀ&#4A81F6ᴏ&#3377F6ʙ&#1B6EF7ᴏ&#0464F8x &7● &cПальмы изобилия исчезли!"
  reload: "&#909EF3ᴢ&#7994F4ᴇ&#618BF5ʀ&#4A81F6ᴏ&#3377F6ʙ&#1B6EF7ᴏ&#0464F8x &7● &aКонфигурация перезагружена!"
  event-started-manually: "&#909EF3ᴢ&#7994F4ᴇ&#618BF5ʀ&#4A81F6ᴏ&#3377F6ʙ&#1B6EF7ᴏ&#0464F8x &7● &aИвент запущен вручную!"
  loot-menu-title: "&6&lНастройка лута"
  no-permission: "&cУ вас нет прав!"